import Head from "next/head";
import { PokemonCard } from "../components/PokemonCard";

type Props = {
  centered: boolean;
  vertical: boolean;
};

export const Home = ({ centered, vertical }: Props) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={`flex ${vertical ? "flex-col" : "flex-row"} ${
          centered ? "items-center justify-center mx-auto" : ""
        } gap-5 h-full w-full`}
      >
        <PokemonCard
          name="Charmander"
          types={["fire"]}
          src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png"
        />
        <PokemonCard
          name="Squirtle"
          types={["water"]}
          src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png"
        />
        <PokemonCard
          name="Bulbasaur"
          types={["grass", "poison"]}
          src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png"
        />
      </div>
    </>
  );
};
